// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://skcefnljjssepphhlduv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNrY2VmbmxqanNzZXBwaGhsZHV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3NDIzNDcsImV4cCI6MjA2MDMxODM0N30.h31WgXfPrw3YcebMUWfPwqvDdTJSej866fvedF99H6M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);